name: bodenbender-work
region: fra
static_sites:
- name: bodenbender-work
  source_dir: /
  github:
    branch: main
    deploy_on_push: true
    repo: KeyboardKobold/bodenbender.work-v3
  environment_slug: node-js
  build_command: npm run build
  output_dir: dist
